apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-2
  namespace: argocd
spec:
  destination:
    namespace: vcluster-cluster-2
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: vcluster
    repoURL: https://charts.loft.sh
    targetRevision: 0.14.2
    helm:
      parameters:
        - name: service.type
          value: LoadBalancer
  syncPolicy:
    syncOptions:
    - CreateNamespace=true