apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-1
  namespace: vm
spec:
  running: false
  template:
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 1024M
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: fedora
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: fedora-1.froystein.jp
            ssh_pwauth: True
            disable_root: false
            ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCjlNh4UPrDac9Yb8R5FOoyB3qo0UNYLS4oGYRY5Cg0gwth0tA0nxvOrirAMj0+RhJ0/O6rg+quh24PYt/Pes6gGUopOyYLvA+i4bHNOAgt91kkqBIjtNFESugcBqVSE565NvKDE+cD8+PLkf4bUMXaMceb1PnGtBwz+URvo9bDVAj/pokkMg11fskIaSikc9nFqYcCs4fXnF3+kOlNL2hdlXKCcD3H5osxgaXoN/O98lsGZZ2BeMcisGwYeGDIxgEFHSUgWrke5JuOod8WkKHF4j67FS6gbiwF7KVAGT2NtVlNbiJ1wu0E4cX05j4j9xo6Uu4HY5roJr+4B7x6f217Je+KwY0EULHCwtKlseNfyQwoDciOC+sDVYXbGsUq4Iya9awpReboeq9Sw6XRu6bq8I9pNBd5kmfezMLRjKCur1B92I92M7MQ0JwX196SKj0HpTa6drXQoln/z0dJatdOZ/WP2Wr7iYWDrjSYHRtgBlQC3kE8Q4lFag5V352fl0U=
        name: cloudinitdisk