apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-influxdb
  namespace: influx
spec:
  selector:
    matchLabels:
      app: telegraf-influxdb
  template:
    metadata:
      labels:
        app: telegraf-influxdb
    spec:
      containers:
        - name: telegraf
          image: telegraf:latest
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
          env:
            - name: INFLUXDB_URL
              value: http://influxdb:8086
            - name: INFLUXDB_DATABASE
              value: metrics
          args: ["--config", "/etc/telegraf/telegraf.conf"]
        - name: influxdb
          image: influxdb:latest
          volumeMounts:
            - name: influxdb-data
              mountPath: /var/lib/influxdb
            - name: tls-certs
              mountPath: /var/lib/influxdb-tls-certs
          env:
            - name: INFLUXDB_DB
              value: metrics
            - name: INFLUXDB_HTTP_AUTH_ENABLED
              value: "false"
            - name: INFLUXDB_HTTP_HTTPS_ENABLED
              value: "false"
          ports:
            - containerPort: 8086
              name: http
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-data-pvc
        - name: tls-certs
          secret:
            secretName: tls-certs-secret
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: influx
spec:
  selector:
    app: telegraf-influxdb
  ports:
    - name: http
      port: 8086
      targetPort: 8086
    - name: https
      port: 8088
      targetPort: 8088
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data-pvc
  namespace: influx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: influx
data:
  telegraf.conf: |
    [global_tags]
      role = "tls-monitor"

    [agent]
      interval = "60s"
      round_interval = true

    [[outputs.influxdb]]
      urls = ["http://influxdb:8086"]
      database = "metrics"
      retention_policy = ""
      write_consistency = "any"
      timeout = "5s"

    [[inputs.x509_cert]]
      sources = ["https://google.com:443"]
      insecure_skip_verify = false
      timeout = "10s"
      name_override = "tls_cert_expiry"
      data_format = "value"
      tagexclude = ["source", "serial_number", "public_key_algorithm", "public_key_size", "subject_common_name", "subject_organization", "subject_organizational_unit", "issuer_common_name", "issuer_organization", "issuer_organizational_unit", "validity_not_before", "validity_not_after"]
