apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/metallb
    repoURL: https://github.com/stianfro/k3os.git
    targetRevision: HEAD