apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-network
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.50-192.168.1.99
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system